site_name: Recipes Repository
site_url: https://thms317.github.io/recipes-repository/

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top

plugins:
  - search
  - awesome-pages
  - recipes

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - css/custom.css

repo_url: https://github.com/thms317/recipes_repository
edit_uri: edit/main/docs/
