site_name: recipes_repository
site_url: https://thms317.github.io/recipes_repository/

nav:
  - Introduction: index.md
  - Recipes:
    - Breakfast: recipes/breakfast.md
    - Starter: recipes/starter.md
    - Main: recipes/main.md
    - Side: recipes/side.md
    - Dessert: recipes/dessert.md
  - Recipe Database: recipe_database.md
  - LLM Instructions: llm_instructions.md

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top

plugins:
  - search
  - recipes:
      recipes_dir: recipes
      images_dir: images

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - css/custom.css

repo_url: https://github.com/thms317/recipes_repository
edit_uri: edit/main/docs/
