site_name: Recipes Repository
site_url: https://thms317.github.io/recipes-repository/

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - glightbox
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - recipes

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - css/custom.css

repo_url: https://github.com/thms317/recipes_repository
edit_uri: edit/main/docs/
